version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./symfony/:/var/www/symfony/
    ports:
      - 8001:80
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: dev
      MESSENGER_TRANSPORT_DSN: "redis://localhost:6379/messages"
      DATABASE_URL: "mysql://root:root@127.0.0.1:3306/sms?serverVersion=5.7"
      APP_SECRET: "26ec6cdeda6c1c4cb6c0a2ba5160ae47"
    volumes:
      - ./symfony/:/var/www/symfony/
    networks:
      - symfony
  mysql:
    image: mysql:5.7.32
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - symfony
networks:
  symfony: